#!/bin/bash

# Start the application httpd instance

# Exit on any errors
set -e

function print_help {
    echo "Usage: $0 app-name namespace uuid"
    echo "Start a running application"

    echo "$0 $@" | logger -p local0.notice -t openshift_origin_httpd_start
    exit 1
}

while getopts 'd' OPTION
do
    case $OPTION in
        d) set -x
        ;;
        ?) print_help
        ;;
    esac
done

[ $# -eq 3 ] || print_help

# if OPENSHIFT_TOMEE_CLUSTER_PROXY_PORT not present try to get it latter
count=0
while [ -z "${OPENSHIFT_TOMEE_CLUSTER_PROXY_PORT}" ]; do
  sleep 1
  if [ -f "${OPENSHIFT_HOMEDIR}/.env/OPENSHIFT_TOMEE_CLUSTER_PROXY_PORT" ]; then
    export OPENSHIFT_TOMEE_CLUSTER_PROXY_PORT=`cat "${OPENSHIFT_HOMEDIR}/.env/OPENSHIFT_TOMEE_CLUSTER_PROXY_PORT"`
  fi
  count=$((count+1))
  if [ $count == 50 ]; then
    break
  fi
done

echo ${OPENSHIFT_GEAR_DNS}:${OPENSHIFT_TOMEE_CLUSTER_PROXY_PORT}
